import {
  USER_LOGGED_IN,
  USER_LOGGED_OUT,
  LOGIN_FAILURE,
  LOGIN_INVALID_CREDENTIALS,
} from "./user.constant";
import {
  EMPLOYEES_FETCH_SUCCESS,
  EMPLOYEES_FETCH_FAILURE,
} from "./employees.constant";

export {
  USER_LOGGED_IN,
  USER_LOGGED_OUT,
  LOGIN_FAILURE,
  LOGIN_INVALID_CREDENTIALS,
  EMPLOYEES_FETCH_SUCCESS,
  EMPLOYEES_FETCH_FAILURE,
};
