const LOGIN_INVALID_CREDENTIALS = "LOGIN_INVALID_CREDENTIALS";
const LOGIN_FAILURE = "LOGIN_FAILURE";
const USER_LOGGED_IN = "USER_LOGGED_IN";
const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export {
  USER_LOGGED_IN,
  USER_LOGGED_OUT,
  LOGIN_FAILURE,
  LOGIN_INVALID_CREDENTIALS,
};
